package org.cipo;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.cipo.template.TemplateEngine;
import org.cipo.tui.ITerminal;
import org.cipo.tui.Terminal;

import com.google.inject.Guice;
import com.google.inject.Injector;

import org.cipo.command.CommandEngine;
import org.cipo.di.modules.ApplicationModule;
import org.cipo.executor.IExecutor;

import groovy.lang.Binding; 
import groovy.lang.GroovyShell; 
public class Cipo {
   
	public static  String VERSION="0.0.1";
	
	
	public static void main(String[] args){
		
		//System.out.println("Cipo Code Generator"+Cipo.VERSION);
		
		Injector injector = Guice.createInjector(new ApplicationModule());
		
		
		TemplateEngine te = new TemplateEngine();
		
		
		IApplication app = (IApplication)injector.getInstance(IApplication.class);
		
		ITerminal term = injector.getInstance(ITerminal.class);
		
		te.printLogo();
		
	    
		
	
				
		CommandEngine cmdEngine = (CommandEngine) injector.getInstance(CommandEngine.class);
		cmdEngine.setArgs(args);
		
		
		IExecutor exec = injector.getInstance(IExecutor.class);
			
		
		
		exec.loadKernel();
		
		exec.execFromResource("script/test.groovy");
		
		
		cmdEngine.run();	
		
	}
}
